databases:
  - name: comUni
    databaseName: dbcu
    user: hrishiraj_mandal
    plan: free

services:
  - type: web
    name: mysite
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "./bin/rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "./bin/rails server"
    envVars:
      - key: postgres://hrishiraj_mandal:zT4md9jDW1pd2USAdLXbLt88NHbFZ1J2@dpg-cm8i0f8cmk4c73924550-a/dbcu
        fromDatabase:
          name: comUni
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
